### ISSUE TITLE
Support Scala 2.11

### ISSUE THREAD

**Issue by tomwadeson** [fthomas/fs2-cron#12]
`fs2-cron` looks perfect for something I'm trying to do. Unfortunately the project I'd like to use it in is tied to 2.11 and `fs2-cron` is currently only published for 2.12.

If it's not a priority for you, would you welcome a PR tackling this?

**Comment by fthomas** [comment]
Yes, of course! :-)

**Comment by fthomas** [comment]
Fixed by #18
