### ISSUE TITLE
Support Scala 2.13

### ISSUE THREAD

**Issue by francisdb** [fthomas/fs2-cron#41]
depends on https://github.com/alonsodomin/cron4s/issues/187

**Comment by gatorcse** [comment]
2.13 support in a milestone: [0.6.0-M2](https://github.com/alonsodomin/cron4s/releases/tag/v0.6.0-M2)

**Comment by fthomas** [comment]
I'll happily take a PR that updates dependencies to milestones or release candidates with 2.13 support. Or we can wait until @scala-steward updates all dependencies to versions with 2.13 support.

**Comment by fthomas** [comment]
fs2-cron 0.2.1 for Scala 2.12 and 2.13 has just been released.
