### ISSUE TITLE
release fs2-cron-cron4s for Scala 3

### ISSUE THREAD

**Issue by hejfelix** [fthomas/fs2-cron#457]
Hi, it looks to me like nothing is blocking a Scala 3 release?

Let me know if there's something I can do to make it happen :) (it's blocking an upgrade for me)

**Comment by fthomas** [comment]
fs2-cron-core, fs2-cron-calev, and fs2-cron-cron-utils are available for Scala 3: https://repo1.maven.org/maven2/eu/timepit/

fs2-cron-cron4s is not available for Scala 3 because cron4s is not yet available for Scala 3: https://repo1.maven.org/maven2/com/github/alonsodomin/cron4s/
